### ISSUE TITLE
Fix Discord Bot Trimming Comment Messages

### ISSUE THREAD

**Issue by Inoxia25** [MLH-Fellowship/pod-3.1.3-team-4#12]
When I post a comment with `github-post-comment`, 
EX-
`github-post-comment Great work!`
Only,
`Your comment: Great has been posted.` is the bot's reply.
And also, only the first word of sentence entered by user is commented on the issue.

**Comment by louisefindlay23** [comment]
Same here, @Inoxia25. Think it's the const `arg` variable in the `main.js` file that strips everything after white-space.

**Comment by Inoxia25** [comment]
@louisefindlay23 yes can be. Gotta look into that!

**Comment by louisefindlay23** [comment]
Is this fixed now, @Inoxia25 by #15?

**Comment by louisefindlay23** [comment]
Will be fixed by #30 for new argument format.
