### ISSUE TITLE
Add Bot Commands to Allow Users to Choose Repo

### ISSUE THREAD

**Issue by louisefindlay23** [MLH-Fellowship/pod-3.1.3-team-4#22]
Add commands to let users change repo by setting owner and repo variables.

**Comment by Inoxia25** [comment]
["This","is","now","working"]

**Comment by Inoxia25** [comment]
Thisisnowworking

**Comment by Inoxia25** [comment]
This is now working

**Comment by Inoxia25** [comment]
This is now working

**Comment by Inoxia25** [comment]
This is now working
