### ISSUE TITLE
Create Pull Request Template

### ISSUE THREAD

**Issue by louisefindlay23** [MLH-Fellowship/pod-3.1.3-team-4#4]
Create a pull request template for descriptive PR descriptions.

Probably copy or use Pod Portfolio one I created as a base.

**Comment by louisefindlay23** [comment]
Happy for anyone to take this on if they want. Just copy the .md file from pod portfolio.

**Comment by louisefindlay23** [comment]
Command-line comment test.

**Comment by louisefindlay23** [comment]
Command-line comment test.

**Comment by louisefindlay23** [comment]
Command-line comment test.

**Comment by louisefindlay23** [comment]
Command-line comment test.

**Comment by louisefindlay23** [comment]
Command-line comment test.

**Comment by Inoxia25** [comment]
Command-line comment test

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot :rocket

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by Inoxia25** [comment]
A test command posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
A test comment posted through the Gitcord Bot!

**Comment by louisefindlay23** [comment]
This

**Comment by louisefindlay23** [comment]
Nice

**Comment by louisefindlay23** [comment]
Test

**Comment by louisefindlay23** [comment]
Test2

**Comment by louisefindlay23** [comment]
Test3

**Comment by louisefindlay23** [comment]
Test4

**Comment by louisefindlay23** [comment]
Great

**Comment by louisefindlay23** [comment]
Great work!

**Comment by louisefindlay23** [comment]
Hi

**Comment by louisefindlay23** [comment]
Issue

**Comment by Inoxia25** [comment]
Great

**Comment by louisefindlay23** [comment]
@dtemir, would you like to work on this?

**Comment by Inoxia25** [comment]
GreatWork!

**Comment by Inoxia25** [comment]
Great Work!

**Comment by Inoxia25** [comment]
Hi This is a New Comment

**Comment by Inoxia25** [comment]
Hi, this new comment is working.

**Comment by louisefindlay23** [comment]
Closes as of #29.
